- name: Restart systemd
  systemd:
    daemon_reload: true

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: Start node_exporter
  systemd:
    name: node_exporter
    state: started

- name: Stop node_exporter
  systemd:
    name: node_exporter
    state: stopped

- name: Enable node_exporter
  systemd:
    name: node_exporter
    enabled: yes