---
  - name: Installing additional packages
    apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
    loop: ['adduser', 'libfontconfig1', 'musl']

  - name: install a deb package Grafana from the internet
    apt: 
      deb: https://dl.grafana.com/oss/release/grafana_{{ version }}_amd64.deb
      state: present
    notify:
      - Start grafana
      - Enable grafana
