---
  - name: Create users prometheus
    user:
      name: prometheus
      create_home: no
      shell: /bin/false

  - name: Create directory for prometheus
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
    loop: 
      - /tmp/prometheus
      - /etc/prometheus
      - /var/lib/prometheus

  - name: Download And Unzipped Prometheus
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
      dest: /tmp/prometheus
      creates: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64
      remote_src: yes

  - name: Copy Bin Files From Unzipped to Prometheus
    copy: 
      src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
      dest: /usr/local/bin/
      remote_src: yes
      mode: preserve
      owner: prometheus
      group: prometheus
    loop: [ 'prometheus', 'promtool' ]

  - name: Copy Conf Files From Unzipped to Prometheus
    copy: 
      src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
      dest: /etc/prometheus/
      remote_src: yes
      mode: preserve
      owner: prometheus
      group: prometheus
    loop: [ 'console_libraries', 'consoles' ]

  - name: Stopping the service prometheus
    systemd:
        name: prometheus
        state: stopped

  - name: Deleting the old configuration file
    file:
        path: /etc/prometheus/prometheus.yml
        state: absent

  - name: Copy Conf Files to Prometheus
    template:
      src=templates/prometheus.yml.j2
      dest=/etc/prometheus/prometheus.yml

  - name: Create File for Prometheus Systemd and Start Prometheus
    template:
      src=templates/prometheus.service.j2
      dest=/etc/systemd/system/prometheus.service
    notify:
      - Restart systemd
      - Restart prometheus
      - Enable prometheus
